fix: prettier errors

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
   pull_request:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
 
 jobs:
   eslint:
@@ -12,35 +12,38 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout branch
-      uses: actions/checkout@v4
+      - name: Checkout branch
+        uses: actions/checkout@v4
 
-    - name: Setup latest version of Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: latest
-        cache: 'npm'
+      - name: Setup latest version of Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: latest
+          cache: "npm"
 
-    - name: Install dependencies
-      run: npm ci
+      - name: Install dependencies
+        run: npm ci
 
-    - run: npm run lint
+      - run: npm run lint
 
   prettier:
     name: Prettier
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout branch
-      uses: actions/checkout@v4
+      - name: Checkout branch
+        uses: actions/checkout@v4
 
-    - name: Setup latest version of Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: latest
-        cache: 'npm'
+      - name: Setup latest version of Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: latest
+          cache: "npm"
 
-    - name: Install dependencies
-      run: npm ci
+      - name: Install dependencies
+        run: npm ci
 
-    - run: npm run prettier
+      - run: |
+          if ! npm run prettier; then
+            echo "::error ::Style issues found, run 'npm run prettier:fix'" && exit 1
+          fi
